### ISSUE TITLE
 uninitialized constant OnlyOfficeRedmine::Message | NameError in Messages#show

### ISSUE THREAD

**Issue by hycesar** [ONLYOFFICE/onlyoffice-redmine#172]
[Action Controller_ Exception caught.pdf](https://github.com/user-attachments/files/15739245/Action.Controller_.Exception.caught.pdf)

Environment:
  Redmine version                5.1.2.stable
  Ruby version                   3.2.2-p53 (2023-03-30) [x64-mingw-ucrt]
  Rails version                  6.1.7.7
  Environment                    development
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
Redmine settings:
  Redmine theme                  Purplemine2 (includes JavaScript)
SCM:
  Git                            2.38.1
  Filesystem                     
Redmine plugins:
  additionals                    3.3.0-main
  custom_users_as_assignees      0.0.4
  easy_baseline                  2.0
  easy_gantt                     2.0
  easy_gantt_pro                 2.0
  easy_mindmup                   2.0
  easy_wbs                       2.0
  flux_mentions                  1.1.0
  mega_calendar                  1.9.6
  redmine_agile                  1.6.8
  redmine_checklists             3.1.23
  redmine_custom_workflows       2.1.0
  redmine_impersonate            2.0.0
  redmine_issue_dynamic_edit     0.9.2
  redmine_issue_view_columns     2.0.3
  redmine_logs                   0.3.0
  redmine_monitoring_controlling 0.1.1
  redmine_oauth                  2.2.0
  redmine_people                 1.6.5
  redmine_percent_done           2.0.0
  redmine_resources              2.0.1
  redmine_xlsx_format_issue_exporter 0.2.1
  redmine_zenedit                2.0.6
  redmineup_tags                 2.0.14
  view_customize                 3.5.1

**Comment by hycesar** [comment]
NameError in Messages#show
 Showing C:/xampp/htdocs/redmine/plugins/onlyoffice_redmine/app/views/messages/show.html.erb where line #18
 raised:
 uninitialized constant OnlyOfficeRedmine::Message
 Extracted source (around line #175):
 173
 174
 175
 176
 177
 178
    view = Views::Messages::Show.new(helpers: helpers)
    container = OnlyOfficeRedmine::Message.new(message: topic)
    view.attachments = setup_link_to_attachments(helpers, user, container)
    replies.each do |message|
 Rails.root: C:/xampp/htdocs/redmine
 Application Trace | 
Framework Trace | 
Full Trace
 plugins/onlyoffice_redmine/app/controllers/only_office_attachments_controller.rb:175:in `show_topic'
 plugins/onlyoffice_redmine/app/views/messages/show.html.erb:18
 lib/redmine/sudo_mode.rb:61:in `sudo_mode'
 Request
 Parameters:
 {"board_id"=>"4", "id"=>"10"}
 Toggle session dump
 Toggle env dump
 Response
 Headers:
 None
