### ISSUE TITLE
Opening Files Error

### ISSUE THREAD

**Issue by valireality** [ONLYOFFICE/onlyoffice-redmine#4]
![image](https://user-images.githubusercontent.com/22134586/144208988-32d3b896-fc19-444a-9864-33b484dfe9d3.png)

**Comment by picman** [comment]
```bash
$ wget http://localhost:3000
--2022-02-10 08:02:34--  http://localhost:3000/
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:3000... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://localhost:3000/login?back_url=http%3A%2F%2Flocalhost%3A3000%2F [following]
--2022-02-10 08:02:34--  http://localhost:3000/login?back_url=http%3A%2F%2Flocalhost%3A3000%2F
Reusing existing connection to localhost:3000.
HTTP request sent, awaiting response... 200 OK
Length: 6338 (6,2K) [text/html]
Saving to: ‘index.html’

index.html                100%[====================================>]   6,19K  --.-KB/s    in 0s      

2022-02-10 08:02:34 (545 MB/s) - ‘index.html’ saved [6338/6338]

$ wget http://localhost:80
--2022-02-10 08:02:43--  http://localhost/
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:80... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: http://localhost/welcome/ [following]
--2022-02-10 08:02:43--  http://localhost/welcome/
Reusing existing connection to localhost:80.
HTTP request sent, awaiting response... 200 OK
Length: 3959 (3,9K) [text/html]
Saving to: ‘index.html.1’

index.html.1              100%[====================================>]   3,87K  --.-KB/s    in 0s      

2022-02-10 08:02:43 (187 MB/s) - ‘index.html.1’ saved [3959/3959]
```

**Comment by picman** [comment]
Only office installed in Docker on localhost, port 80. Test example from the main site works fine. Redmine installed on localhost, port 3000 (Webrick).

**Comment by picman** [comment]
In the docker container I can see the following error related to the opening failure:
```[ERROR] nodeJS - error downloadFile:url=http://localhost:3000/onlyoffice/download/100825?key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdHRhY2htZW50X2lkIjoxMDA4MjUsInR5cGUiOiJkb3dubG9hZCIsInVzZXJpZCI6OX0.0liaFFsVr_2xC1--39pqEw8DW_mCQIDR-7QDVwir3A4;attempt=3;code:null;connect:null;(id=100825_2022_02_10_06_43_42_UTC)
Error: Error response: statusCode:404; headers:{"x-powered-by":"Express","access-control-allow-origin":"*","content-type":"text/html; charset=utf-8","content-length":"953","etag":"W/\"3b9-Zsrwh4/5x1k7MttpJDzAJeaSkLQ\"","date":"Thu, 10 Feb 2022 07:29:44 GMT","connection":"keep-alive","keep-alive":"timeout=5"};
    at Request.fResponse (/snapshot/server/build/server/Common/sources/utils.js)
    at Request.emit (events.js:400:28)
    at Request.onRequestResponse (/snapshot/server/build/server/Common/node_modules/request/request.js:1059:10)
    at ClientRequest.emit (events.js:400:28)
    at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at Socket.socketOnData (_http_client.js:515:22)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

```

**Comment by iamwildtuna** [comment]
У меня похожая ошибки. В .../docservice/out.log не нравится, что у меня 301 редирект с http на https. Так как Redmine находится в контейнере под http, а https уже на реверсе через nginx пробрасывается.

```
[2022-03-23T21:00:55.464] [ERROR] nodeJS - postData error: docId = 3474_2022_03_23_18_03_24_UTC;url = http://redminehost.ru/onlyoffice/callback/3474/bb196c9e7694a1281f80e43b7b62775b4287d611?key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdHRhY2htZW50X2lkIjozNDc0LCJ0eXBlIjoiY2FsbGJhY2sifQ.4ABpT7YXb19OWPGRTul724ZJceZ90i1YEGxG8Qbbp30;data = {"key":"3474_2022_03_23_18_03_24_UTC","status":1,"users":["3"],"actions":[{"type":0,"userid":"3"}]}
Error: Error response: statusCode:301; headers:{"server":"nginx/1.18.0","date":"Wed, 23 Mar 2022 21:00:55 GMT","content-type":"text/html","content-length":"169","connection":"keep-alive","location":"https://redminehost.ru/onlyoffice/callback/3474/bb196c9e7694a1281f80e43b7b62775b4287d611?key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdHRhY2htZW50X2lkIjozNDc0LCJ0eXBlIjoiY2FsbGJhY2sifQ.4ABpT7YXb19OWPGRTul724ZJceZ90i1YEGxG8Qbbp30"}; body:
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.18.0</center>
</body>
</html>

    at Request._callback (/snapshot/server/build/server/Common/sources/utils.js)
    at Request.callback (/snapshot/server/build/server/Common/node_modules/request/request.js:185:22)
    at Request.emit (events.js:400:28)
    at Request.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:400:28)
    at IncomingMessage.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:519:28)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
[2022-03-23T21:00:56.404] [ERROR] nodeJS - postData error: docId = 3474_2022_03_23_18_03_24_UTC;url = http://redminehost.ru/onlyoffice/callback/3474/bb196c9e7694a1281f80e43b7b62775b4287d611?key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdHRhY2htZW50X2lkIjozNDc0LCJ0eXBlIjoiY2FsbGJhY2sifQ.n-NAQiW4UtEC8yrg9CQyeln2eVzmbVVHjZDWHm6XHDs;data = {"key":"3474_2022_03_23_18_03_24_UTC","status":1,"users":["3"],"actions":[{"type":1,"userid":"3"}]}
Error: Error response: statusCode:301; headers:{"server":"nginx/1.18.0","date":"Wed, 23 Mar 2022 21:00:56 GMT","content-type":"text/html","content-length":"169","connection":"keep-alive","location":"https://redminehost.ru/onlyoffice/callback/3474/bb196c9e7694a1281f80e43b7b62775b4287d611?key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdHRhY2htZW50X2lkIjozNDc0LCJ0eXBlIjoiY2FsbGJhY2sifQ.n-NAQiW4UtEC8yrg9CQyeln2eVzmbVVHjZDWHm6XHDs"}; body:
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.18.0</center>
</body>
</html>

    at Request._callback (/snapshot/server/build/server/Common/sources/utils.js)
    at Request.callback (/snapshot/server/build/server/Common/node_modules/request/request.js:185:22)
    at Request.emit (events.js:400:28)
    at Request.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:400:28)
    at IncomingMessage.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:519:28)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

**Comment by iamwildtuna** [comment]
У меня развернут Redmine этим docker-compose рецептом https://github.com/sameersbn/docker-redmine#enabling-https-support. В моем случае проблема устранилась после передачи переменной окружения REDMINE_HTTPS=true.

**Comment by SergeyKorneyev** [comment]
Please check if the issue persists with the recently released version 3.0 of the plugin.

**Comment by Rita-Bubnova** [comment]
This issue was closed due no response.
