### ISSUE TITLE
V2.0.0 bugs

### ISSUE THREAD

**Issue by drcyberg** [ONLYOFFICE/onlyoffice-redmine#43]
Hi Masters!

I installed new version plugin, and it works half way. Here is the production.log files.

1. bug: Create new document in Redmine:
- _"Completed 500 Internal Server Error in 25ms (ActiveRecord: 3.7ms)"_
- _"No such file or directory @ rb_sysopen - /opt/redmine/plugins/onlyoffice_redmine/assets/document-templates/en-US/new.docx"_
2. bug: Create new document in file manager. In the Redmine plugin settings say:
- _"ONLYOFFICE cannot be reached. Please contact admin"_
- If delete new.docx file, after works fine again
3. bug: Conversion error.
- _"/opt/redmine/plugins/onlyoffice_redmine/app/models/service_converter.rb:74:in `get_response_uri': ConvertError: ErrorCode = -4 (RuntimeError)"_

Big thanks and regards: DrCyberg

**Comment by Eloncase** [comment]
Hi @drcyberg.

1. Were you trying to install it from releases or manually? We are using git submodule for our document templates and it seems that it is not present in your case. You might've forgot using `--recursive` flag if you were trying to install it manually.

2. I'll try to reproduce it.

3. I will need logs from both redmine and document server for that one. You can find error codes [here](https://api.onlyoffice.com/editors/conversionapi#error-codes). `-4` means that document server couldn't download file from redmine. Does the editing work?

**Comment by Eloncase** [comment]
Couldn't reproduce. Which version of plugin are you using?

**Comment by LinneyS** [comment]
Could you please specify if the problem recurs or we can close the topic?

**Comment by rubensff** [comment]
olá, estou tendo o mesmo problema reportado.
Usando a versâo 2.0 com redmine 5.


F, [2023-04-03T13:43:31.206597 #22783] FATAL -- : [26e78121-7671-4372-af0b-584337872508]   
[26e78121-7671-4372-af0b-584337872508] Errno::ENOENT (No such file or directory @ rb_sysopen - /var/www/redmine/plugins/onlyoffice_redmine/assets/document-templates/en-US/new.docx):
[26e78121-7671-4372-af0b-584337872508]   
[26e78121-7671-4372-af0b-584337872508] plugins/onlyoffice_redmine/app/controllers/onlyoffice_create_controller.rb:44:in `initialize'
[26e78121-7671-4372-af0b-584337872508] plugins/onlyoffice_redmine/app/controllers/onlyoffice_create_controller.rb:44:in `open'
[26e78121-7671-4372-af0b-584337872508] plugins/onlyoffice_redmine/app/controllers/onlyoffice_create_controller.rb:44:in `create_attachment_from_template_file'
[26e78121-7671-4372-af0b-584337872508] plugins/onlyoffice_redmine/app/controllers/onlyoffice_create_controller.rb:30:in 
[26e78121-7671-4372-af0b-584337872508] lib/redmine/sudo_mode.rb:61:in `sudo_mode'

[production.log](https://github.com/ONLYOFFICE/onlyoffice-redmine/files/11142758/production.log)

**Comment by kaizen95** [comment]
Hello
<img width="620" alt="download as file" src="https://user-images.githubusercontent.com/10494434/232956519-56238f6c-f6b1-4719-8198-1803cbbcac91.png">
Bug #4 occurs when trying to download as file(to PDF).

redmine 4.0.6(Apache2:80), onlyoffice-redmine v2.1.0, onlyoffice(nginx:8080, not docker)
plugin Settings all full(URL use outside domain)

Edit in onlyoffice is possible, but the converted PDF cannot be downloaded.

**production.log**
```
plugins/onlyoffice_redmine/app/controllers/onlyoffice_controller.rb:44:in `download'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'
/usr/share/redmine/plugins/onlyoffice_redmine/app/helpers/service_converter.rb:73:in `get_response_uri': ConvertError: ErrorCode = -4 (RuntimeError)
	from /usr/share/redmine/plugins/onlyoffice_redmine/app/helpers/service_converter.rb:63:in `get_converted_uri'
	from /usr/share/redmine/plugins/onlyoffice_redmine/app/controllers/onlyoffice_convert_controller.rb:39:in `convert'
	from /usr/share/rubygems-integration/all/gems/actionpack-5.2.3/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
	from /usr/share/rubygems-integration/all/gems/actionpack-5.2.3/lib/abstract_controller/base.rb:194:in `process_action'
	from /usr/share/rubygems-integration/all/gems/actionpack-5.2.3/lib/action_controller/metal/rendering.rb:30:in `process_action'
	from /usr/share/rubygems-integration/all/gems/actionpack-5.2.3/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
	from /usr/share/rubygems-integration/all/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:109:in `block in run_callbacks'
	from /usr/share/redmine/lib/redmine/sudo_mode.rb:63:in `sudo_mode'
	from /usr/share/rubygems-integration/all/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
	from /usr/share/rubygems-integration/all/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:136:in `run_callbacks'
	from /usr/share/rubygems-integration/all/gems/actionpack-5.2.3/lib/abstract_controller/callbacks.rb:41:in `process_action'
	from /usr/share/rubygems-integration/all/gems/actionpack-5.2.3/lib/action_controller/metal/rescue.rb:22:in `process_action'
	from /usr/share/rubygems-integration/all/gems/actionpack-5.2.3/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
	from /usr/share/rubygems-integration/all/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `block in instrument'
	from /usr/share/rubygems-integration/all/gems/activesupport-5.2.3/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
	from /usr/share/rubygems-integration/all/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `instrument'
	from /usr/share/rubygems-integration/all/gems/actionpack-5.2.3/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
	from /usr/share/rubygems-integration/all/gems/actionpack-5.2.3/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
	from /usr/share/rubygems-integration/all/gems/activerecord-5.2.3/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
	from /usr/share/rubygems-integration/all/gems/actionpack-5.2.3/lib/abstract_controller/base.rb:134:in `process'
	from /usr/share/rubygems-integration/all/gems/actionview-5.2.3/lib/action_view/rendering.rb:32:in `process'
	from /usr/share/rubygems-integration/all/gems/actionpack-5.2.3/lib/action_controller/metal.rb:191:in `dispatch'
	from /usr/share/rubygems-integration/all/gems/actionpack-5.2.3/lib/action_controller/metal.rb:252:in `dispatch'
	from /usr/share/rubygems-integration/all/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
	from /usr/share/rubygems-integration/all/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:34:in `serve'
	from /usr/share/rubygems-integration/all/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:52:in `block in serve'
	from /usr/share/rubygems-integration/all/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:35:in `each'
	from /usr/share/rubygems-integration/all/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:35:in `serve'
	from /usr/share/rubygems-integration/all/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:840:in `call'
	from /var/lib/gems/2.7.0/gems/rack-raw-upload-1.1.1/lib/rack/raw_upload.rb:18:in `call'
	from /usr/lib/ruby/vendor_ruby/rack/tempfile_reaper.rb:15:in `call'
	from /usr/lib/ruby/vendor_ruby/rack/etag.rb:25:in `call'
	from /usr/lib/ruby/vendor_ruby/rack/conditional_get.rb:38:in `call'
	from /usr/lib/ruby/vendor_ruby/rack/head.rb:12:in `call'
	from /usr/share/rubygems-integration/all/gems/actionpack-5.2.3/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
	from /usr/lib/ruby/vendor_ruby/rack/session/abstract/id.rb:232:in `context'
	from /usr/lib/ruby/vendor_ruby/rack/session/abstract/id.rb:226:in `call'
	from /usr/share/rubygems-integration/all/gems/actionpack-5.2.3/lib/action_dispatch/middleware/cookies.rb:670:in `call'
	from /usr/share/rubygems-integration/all/gems/actionpack-5.2.3/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
	from /usr/share/rubygems-integration/all/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:98:in `run_callbacks'
	from /usr/share/rubygems-integration/all/gems/actionpack-5.2.3/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
	from /usr/share/rubygems-integration/all/gems/actionpack-5.2.3/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
	from /usr/share/rubygems-integration/all/gems/actionpack-5.2.3/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
	from /usr/share/rubygems-integration/all/gems/railties-5.2.3/lib/rails/rack/logger.rb:38:in `call_app'
	from /usr/share/rubygems-integration/all/gems/railties-5.2.3/lib/rails/rack/logger.rb:26:in `block in call'
	from /usr/share/rubygems-integration/all/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `block in tagged'
	from /usr/share/rubygems-integration/all/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:28:in `tagged'
	from /usr/share/rubygems-integration/all/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `tagged'
	from /usr/share/rubygems-integration/all/gems/railties-5.2.3/lib/rails/rack/logger.rb:26:in `call'
	from /usr/share/rubygems-integration/all/gems/actionpack-5.2.3/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
	from /usr/lib/ruby/vendor_ruby/request_store/middleware.rb:19:in `call'
	from /usr/share/rubygems-integration/all/gems/actionpack-5.2.3/lib/action_dispatch/middleware/request_id.rb:27:in `call'
	from /usr/lib/ruby/vendor_ruby/rack/method_override.rb:22:in `call'
	from /usr/lib/ruby/vendor_ruby/rack/runtime.rb:22:in `call'
	from /usr/share/rubygems-integration/all/gems/activesupport-5.2.3/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
	from /usr/share/rubygems-integration/all/gems/actionpack-5.2.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
	from /usr/share/rubygems-integration/all/gems/actionpack-5.2.3/lib/action_dispatch/middleware/static.rb:127:in `call'
	from /usr/lib/ruby/vendor_ruby/rack/content_length.rb:15:in `call'
	from /usr/lib/ruby/vendor_ruby/rack/sendfile.rb:111:in `call'
	from /usr/share/rubygems-integration/all/gems/railties-5.2.3/lib/rails/engine.rb:524:in `call'
	from /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
	from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:160:in `accept_and_process_next_request'
	from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
	from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
	from /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

**converter/out.log**
```
[2023-04-19T11:47:09.395] [ERROR] [localhost] [conv_5_2023_04_15_02_18_13_UTC_pdf] [userId] nodeJS - error downloadFile:url=http://example.redmine.page/onlyoffice/download/5?key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdHRhY2htZW50X2lkIjo1LCJ0eXBlIjoiZG93bmxvYWQiLCJ1c2VyaWQiOjV9.mxHO16kSjf_OIwe_GHnu0dBkn1JD74vlA_5aHE12EcU;attempt=3;code:undefined;connect:undefined Error: Error response: statusCode:500; headers:{"date":"Wed, 19 Apr 2023 02:47:09 GMT","server":"Apache/2.4.41 (Ubuntu)","x-request-id":"33011733-5e46-4718-9b8b-66fc911b18e2","x-runtime":"0.007321","x-powered-by":"Phusion Passenger 5.0.30","content-length":"648","status":"500 Internal Server Error","connection":"close","content-type":"text/html; charset=utf-8"};
    at Request.fResponse (/snapshot/server/build/server/Common/sources/utils.js)
    at Request.emit (events.js:400:28)
    at Request.onRequestResponse (/snapshot/server/build/server/Common/node_modules/request/request.js:1059:10)
    at ClientRequest.emit (events.js:400:28)
    at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)
    at Socket.socketOnData (_http_client.js:515:22)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
    at Socket.Readable.push (internal/streams/readable.js:206:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by SergeyKorneyev** [comment]
Please check if the issue persists with the recently released version 3.0 of the plugin.

**Comment by LinneyS** [comment]
This issue was closed due to no response.
