### ISSUE TITLE
JSON::ParserError

### ISSUE THREAD

**Issue by nikosfrangakis** [ONLYOFFICE/onlyoffice-redmine#44]
On the enviroment mentioned at the end, i get the following error on the logs and i cannot connect to any onlyoffice server (mine or the public one).
```
I, [2023-01-02T19:39:48.480487 #455612]  INFO -- : [03377ca2-af08-4aa6-aa5a-12ac8a7a27e9] Started POST "/onlyoffice/check/settings" for 83.235.111.244 at 2023-01-02 19:39:48 +0200
I, [2023-01-02T19:39:48.486505 #455612]  INFO -- : [03377ca2-af08-4aa6-aa5a-12ac8a7a27e9] Processing by OnlyofficeController#check_settings as */*
I, [2023-01-02T19:39:48.486685 #455612]  INFO -- : [03377ca2-af08-4aa6-aa5a-12ac8a7a27e9]   Parameters: {"url"=>"https://onlinedocs.onlyoffice.com/", "editor_inner_url"=>"", "redmine_url"=>"https://redmine.iccs.gr/", "secret"=>"sn2puSUF7muF5Jas", "cert"=>false, "demo"=>true}
I, [2023-01-02T19:39:48.505609 #455612]  INFO -- : [03377ca2-af08-4aa6-aa5a-12ac8a7a27e9]   Current user: nikos (id=3)
I, [2023-01-02T19:39:48.509265 #455612]  INFO -- : [03377ca2-af08-4aa6-aa5a-12ac8a7a27e9] Saving attachment '/opt/www/redminev5/files/2023/01/230102193948_OnlyOfficeCheakConvertService.docx' (6940 bytes)
I, [2023-01-02T19:39:49.402498 #461757]  INFO -- : [81ce76b7-7163-4c22-91fd-038584e4de86] Started GET "/onlyoffice/download/18254?key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdHRhY2htZW50X2lkIjoxODI1NCwidHlwZSI6ImRvd25sb2FkIiwidXNlcmlkIjozfQ.zipJ_0Ub9vohhE3v5G-Skw5Sttr1Ny6fc5MDqCJAf3k" for 85.195.73.41 at 2023-01-02 19:39:49 +0200
I, [2023-01-02T19:39:49.415561 #461757]  INFO -- : [81ce76b7-7163-4c22-91fd-038584e4de86] Processing by OnlyofficeController#download as HTML
I, [2023-01-02T19:39:49.415919 #461757]  INFO -- : [81ce76b7-7163-4c22-91fd-038584e4de86]   Parameters: {"key"=>"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdHRhY2htZW50X2lkIjoxODI1NCwidHlwZSI6ImRvd25sb2FkIiwidXNlcmlkIjozfQ.zipJ_0Ub9vohhE3v5G-Skw5Sttr1Ny6fc5MDqCJAf3k", "id"=>"18254"}
I, [2023-01-02T19:39:49.427342 #461757]  INFO -- : [81ce76b7-7163-4c22-91fd-038584e4de86]   Current user: anonymous
I, [2023-01-02T19:39:49.430605 #461757]  INFO -- : [81ce76b7-7163-4c22-91fd-038584e4de86] Completed 500 Internal Server Error in 14ms (ActiveRecord: 1.5ms | Allocations: 694)
F, [2023-01-02T19:39:49.431373 #461757] FATAL -- : [81ce76b7-7163-4c22-91fd-038584e4de86]
[81ce76b7-7163-4c22-91fd-038584e4de86] JSON::ParserError (809: unexpected token at ''):
[81ce76b7-7163-4c22-91fd-038584e4de86]
[81ce76b7-7163-4c22-91fd-038584e4de86] plugins/onlyoffice_redmine/app/controllers/onlyoffice_controller.rb:46:in `download'
[81ce76b7-7163-4c22-91fd-038584e4de86] lib/redmine/sudo_mode.rb:61:in `sudo_mode'
[81ce76b7-7163-4c22-91fd-038584e4de86] plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:54:in `call'
```
any ideas to the source of the problem?
kind regards,
Nikos

Environment:
  Redmine version                5.0.4.stable.22007
  Ruby version                   3.0.4-p208 (2022-04-12) [x86_64-linux]
  Rails version                  6.1.7
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
Redmine settings:
  Redmine theme                  Default
SCM:
  Subversion                     1.14.1
  Git                            2.34.1
  Filesystem                     
Redmine plugins:
  onlyoffice_redmine             2.0.0
  redmine_ckeditor               1.2.4
  redmine_dmsf                   3.0.7

**Comment by Eloncase** [comment]
Hello @nikosfrangakis.
Can you also send logs from document server?

And how is JWT configured on document server side? Are you using `inBody` parameter?

**Comment by nikosfrangakis** [comment]
@Eloncase here are the logs:
**redmine**:

I, [2023-01-27T22:01:35.793283 #418147]  INFO -- : [dc6f7025-58e2-4ea6-90c4-0a9786594431] Started GET "/documents/61" for 83.235.111.244 at 2023-01-27 22:01:35 +0200
I, [2023-01-27T22:01:35.793537 #424157]  INFO -- : [7d7c0383-ecdf-4252-a105-c178dcf22989] Started GET "/onlyoffice/editor/18514" for 83.235.111.244 at 2023-01-27 22:01:35 +0200
I, [2023-01-27T22:01:35.795843 #424157]  INFO -- : [7d7c0383-ecdf-4252-a105-c178dcf22989] Processing by OnlyofficeController#editor as HTML
I, [2023-01-27T22:01:35.796043 #424157]  INFO -- : [7d7c0383-ecdf-4252-a105-c178dcf22989]   Parameters: {"id"=>"18514"}
I, [2023-01-27T22:01:35.796416 #418147]  INFO -- : [dc6f7025-58e2-4ea6-90c4-0a9786594431] Processing by DocumentsController#show as HTML
I, [2023-01-27T22:01:35.796634 #418147]  INFO -- : [dc6f7025-58e2-4ea6-90c4-0a9786594431]   Parameters: {"id"=>"61"}
I, [2023-01-27T22:01:35.804256 #424157]  INFO -- : [7d7c0383-ecdf-4252-a105-c178dcf22989]   Current user: nikos (id=3)
I, [2023-01-27T22:01:35.804780 #418147]  INFO -- : [dc6f7025-58e2-4ea6-90c4-0a9786594431]   Current user: nikos (id=3)
W, [2023-01-27T22:01:35.810151 #424157]  WARN -- : [7d7c0383-ecdf-4252-a105-c178dcf22989] DEPRECATION WARNING: User.rss_key is deprecated and will be removed in Redmine 6.0. Please use User.atom_key instead. (called from get_callback_url at /opt/www/redminev5/plugins/onlyoffice_redmine/app/models/document_helper.rb:47)
I, [2023-01-27T22:01:35.814035 #424157]  INFO -- : [7d7c0383-ecdf-4252-a105-c178dcf22989]   Rendered plugins/onlyoffice_redmine/app/views/onlyoffice/editor.html.erb within layouts/base (Duration: 0.9ms | Allocations: 492)
I, [2023-01-27T22:01:35.822806 #418147]  INFO -- : [dc6f7025-58e2-4ea6-90c4-0a9786594431]   Rendered documents/show.html.erb (Duration: 9.8ms | Allocations: 3426)
I, [2023-01-27T22:01:35.825951 #418147]  INFO -- : [dc6f7025-58e2-4ea6-90c4-0a9786594431]   Rendered plugins/onlyoffice_redmine/app/views/documents/show.html.erb within layouts/base (Duration: 13.1ms | Allocations: 5041)
I, [2023-01-27T22:01:35.836809 #424157]  INFO -- : [7d7c0383-ecdf-4252-a105-c178dcf22989]   Rendered layout layouts/base.html.erb (Duration: 23.7ms | Allocations: 11367)
I, [2023-01-27T22:01:35.837308 #424157]  INFO -- : [7d7c0383-ecdf-4252-a105-c178dcf22989] Completed 200 OK in 41ms (Views: 21.8ms | ActiveRecord: 5.9ms | Allocations: 14819)
I, [2023-01-27T22:01:35.846382 #418147]  INFO -- : [dc6f7025-58e2-4ea6-90c4-0a9786594431]   Rendered layout layouts/base.html.erb (Duration: 33.6ms | Allocations: 15362)
I, [2023-01-27T22:01:35.846853 #418147]  INFO -- : [dc6f7025-58e2-4ea6-90c4-0a9786594431] Completed 200 OK in 50ms (Views: 30.7ms | ActiveRecord: 6.3ms | Allocations: 18110)
I, [2023-01-27T22:01:36.668323 #418147]  INFO -- : [15d5ebf1-cdb7-4755-bdaf-a223cb31f430] Started POST "/onlyoffice/callback/18514/d01cf5c316e14ea2378fc94f6684cc83cc4ccd53?key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdHRhY2htZW50X2lkIjoxODUxNCwidHlwZSI6ImNhbGxiYWNrIn0.f_h7qiLmj5RYa50WAooOl7zshlKTmmq9FmGpNdZlte8" for 147.102.5.81 at 2023-01-27 22:01:36 +0200
I, [2023-01-27T22:01:36.671261 #418147]  INFO -- : [15d5ebf1-cdb7-4755-bdaf-a223cb31f430] Processing by OnlyofficeController#callback as HTML
I, [2023-01-27T22:01:36.671653 #418147]  INFO -- : [15d5ebf1-cdb7-4755-bdaf-a223cb31f430]   Parameters: {"key"=>"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdHRhY2htZW50X2lkIjoxODUxNCwidHlwZSI6ImNhbGxiYWNrIn0.f_h7qiLmj5RYa50WAooOl7zshlKTmmq9FmGpNdZlte8", "status"=>1, "users"=>["3"], "actions"=>[{"type"=>1, "userid"=>"3"}], "token"=>"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXkiOiIxODUxNF8yMDIzXzAxXzI3XzE5XzU5XzI5X1VUQyIsInN0YXR1cyI6MSwidXNlcnMiOlsiMyJdLCJhY3Rpb25zIjpbeyJ0eXBlIjoxLCJ1c2VyaWQiOiIzIn1dLCJpYXQiOjE2NzQ4NDk2OTYsImV4cCI6MTY3NDg0OTk5Nn0.QHJyoA85JFlFYhssrue-TngwVd4a_d6VoPtrPYhNDmI", "id"=>"18514", "rss"=>"d01cf5c316e14ea2378fc94f6684cc83cc4ccd53"}
I, [2023-01-27T22:01:36.678913 #418147]  INFO -- : [15d5ebf1-cdb7-4755-bdaf-a223cb31f430]   Current user: anonymous
I, [2023-01-27T22:01:36.685337 #418147]  INFO -- : [15d5ebf1-cdb7-4755-bdaf-a223cb31f430] Completed 500 Internal Server Error in 13ms (ActiveRecord: 3.2ms | Allocations: 1075)
F, [2023-01-27T22:01:36.686500 #418147] FATAL -- : [15d5ebf1-cdb7-4755-bdaf-a223cb31f430]
[15d5ebf1-cdb7-4755-bdaf-a223cb31f430] JSON::ParserError (809: unexpected token at ''):
[15d5ebf1-cdb7-4755-bdaf-a223cb31f430]
[15d5ebf1-cdb7-4755-bdaf-a223cb31f430] plugins/onlyoffice_redmine/app/controllers/onlyoffice_controller.rb:108:in `callback'
[15d5ebf1-cdb7-4755-bdaf-a223cb31f430] lib/redmine/sudo_mode.rb:61:in `sudo_mode'
[15d5ebf1-cdb7-4755-bdaf-a223cb31f430] plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:54:in `call'
I, [2023-01-27T22:01:36.720614 #418147]  INFO -- : [88cafb5e-6604-4e4f-886b-87ae66048888] Started GET "/onlyoffice/download/18514?key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdHRhY2htZW50X2lkIjoxODUxNCwidHlwZSI6ImRvd25sb2FkIiwidXNlcmlkIjozfQ.n95BopN99HnM83i9pc2Zi1FKnldosBIFyuAfAFp3xKk" for 147.102.5.81 at 2023-01-27 22:01:36 +0200
I, [2023-01-27T22:01:36.723610 #418147]  INFO -- : [88cafb5e-6604-4e4f-886b-87ae66048888] Processing by OnlyofficeController#download as HTML
I, [2023-01-27T22:01:36.723850 #418147]  INFO -- : [88cafb5e-6604-4e4f-886b-87ae66048888]   Parameters: {"key"=>"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdHRhY2htZW50X2lkIjoxODUxNCwidHlwZSI6ImRvd25sb2FkIiwidXNlcmlkIjozfQ.n95BopN99HnM83i9pc2Zi1FKnldosBIFyuAfAFp3xKk", "id"=>"18514"}
I, [2023-01-27T22:01:36.729531 #418147]  INFO -- : [88cafb5e-6604-4e4f-886b-87ae66048888]   Current user: anonymous
I, [2023-01-27T22:01:36.733568 #418147]  INFO -- : [88cafb5e-6604-4e4f-886b-87ae66048888] Completed 500 Internal Server Error in 9ms (ActiveRecord: 2.6ms | Allocations: 1094)
F, [2023-01-27T22:01:36.734261 #418147] FATAL -- : [88cafb5e-6604-4e4f-886b-87ae66048888]
[88cafb5e-6604-4e4f-886b-87ae66048888] JSON::ParserError (809: unexpected token at ''):
[88cafb5e-6604-4e4f-886b-87ae66048888]
[88cafb5e-6604-4e4f-886b-87ae66048888] plugins/onlyoffice_redmine/app/controllers/onlyoffice_controller.rb:46:in `download'
[88cafb5e-6604-4e4f-886b-87ae66048888] lib/redmine/sudo_mode.rb:61:in `sudo_mode'
[88cafb5e-6604-4e4f-886b-87ae66048888] plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:54:in `call'
I, [2023-01-27T22:01:37.756449 #418147]  INFO -- : [a13b0b87-09b3-40ff-b38b-06dd3115396e] Started GET "/onlyoffice/download/18514?key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdHRhY2htZW50X2lkIjoxODUxNCwidHlwZSI6ImRvd25sb2FkIiwidXNlcmlkIjozfQ.n95BopN99HnM83i9pc2Zi1FKnldosBIFyuAfAFp3xKk" for 147.102.5.81 at 2023-01-27 22:01:37 +0200
I, [2023-01-27T22:01:37.758693 #418147]  INFO -- : [a13b0b87-09b3-40ff-b38b-06dd3115396e] Processing by OnlyofficeController#download as HTML
I, [2023-01-27T22:01:37.758923 #418147]  INFO -- : [a13b0b87-09b3-40ff-b38b-06dd3115396e]   Parameters: {"key"=>"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdHRhY2htZW50X2lkIjoxODUxNCwidHlwZSI6ImRvd25sb2FkIiwidXNlcmlkIjozfQ.n95BopN99HnM83i9pc2Zi1FKnldosBIFyuAfAFp3xKk", "id"=>"18514"}
I, [2023-01-27T22:01:37.766054 #418147]  INFO -- : [a13b0b87-09b3-40ff-b38b-06dd3115396e]   Current user: anonymous
I, [2023-01-27T22:01:37.771439 #418147]  INFO -- : [a13b0b87-09b3-40ff-b38b-06dd3115396e] Completed 500 Internal Server Error in 12ms (ActiveRecord: 3.2ms | Allocations: 1094)
F, [2023-01-27T22:01:37.772142 #418147] FATAL -- : [a13b0b87-09b3-40ff-b38b-06dd3115396e]
[a13b0b87-09b3-40ff-b38b-06dd3115396e] JSON::ParserError (809: unexpected token at ''):
[a13b0b87-09b3-40ff-b38b-06dd3115396e]
[a13b0b87-09b3-40ff-b38b-06dd3115396e] plugins/onlyoffice_redmine/app/controllers/onlyoffice_controller.rb:46:in `download'
[a13b0b87-09b3-40ff-b38b-06dd3115396e] lib/redmine/sudo_mode.rb:61:in `sudo_mode'
[a13b0b87-09b3-40ff-b38b-06dd3115396e] plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:54:in `call'
I, [2023-01-27T22:01:38.791711 #418147]  INFO -- : [d12b798e-fd4f-4a26-adfa-f29141f64e1a] Started GET "/onlyoffice/download/18514?key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdHRhY2htZW50X2lkIjoxODUxNCwidHlwZSI6ImRvd25sb2FkIiwidXNlcmlkIjozfQ.n95BopN99HnM83i9pc2Zi1FKnldosBIFyuAfAFp3xKk" for 147.102.5.81 at 2023-01-27 22:01:38 +0200
I, [2023-01-27T22:01:38.793780 #418147]  INFO -- : [d12b798e-fd4f-4a26-adfa-f29141f64e1a] Processing by OnlyofficeController#download as HTML
I, [2023-01-27T22:01:38.794003 #418147]  INFO -- : [d12b798e-fd4f-4a26-adfa-f29141f64e1a]   Parameters: {"key"=>"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdHRhY2htZW50X2lkIjoxODUxNCwidHlwZSI6ImRvd25sb2FkIiwidXNlcmlkIjozfQ.n95BopN99HnM83i9pc2Zi1FKnldosBIFyuAfAFp3xKk", "id"=>"18514"}
I, [2023-01-27T22:01:38.799995 #418147]  INFO -- : [d12b798e-fd4f-4a26-adfa-f29141f64e1a]   Current user: anonymous
I, [2023-01-27T22:01:38.805022 #418147]  INFO -- : [d12b798e-fd4f-4a26-adfa-f29141f64e1a] Completed 500 Internal Server Error in 11ms (ActiveRecord: 2.7ms | Allocations: 1094)
F, [2023-01-27T22:01:38.805900 #418147] FATAL -- : [d12b798e-fd4f-4a26-adfa-f29141f64e1a]
[d12b798e-fd4f-4a26-adfa-f29141f64e1a] JSON::ParserError (809: unexpected token at ''):
[d12b798e-fd4f-4a26-adfa-f29141f64e1a]
[d12b798e-fd4f-4a26-adfa-f29141f64e1a] plugins/onlyoffice_redmine/app/controllers/onlyoffice_controller.rb:46:in `download'
[d12b798e-fd4f-4a26-adfa-f29141f64e1a] lib/redmine/sudo_mode.rb:61:in `sudo_mode'
[d12b798e-fd4f-4a26-adfa-f29141f64e1a] plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:54:in `call'
I, [2023-01-27T22:01:41.980572 #418147]  INFO -- : [1086c29d-9259-4ad7-8f68-072709085665] Started GET "/documents/61" for 83.235.111.244 at 2023-01-27 22:01:41 +0200
I, [2023-01-27T22:01:41.982899 #418147]  INFO -- : [1086c29d-9259-4ad7-8f68-072709085665] Processing by DocumentsController#show as HTML
I, [2023-01-27T22:01:41.983118 #418147]  INFO -- : [1086c29d-9259-4ad7-8f68-072709085665]   Parameters: {"id"=>"61"}
I, [2023-01-27T22:01:41.991762 #418147]  INFO -- : [1086c29d-9259-4ad7-8f68-072709085665]   Current user: nikos (id=3)
I, [2023-01-27T22:01:42.016662 #418147]  INFO -- : [1086c29d-9259-4ad7-8f68-072709085665]   Rendered documents/show.html.erb (Duration: 17.3ms | Allocations: 3426)
I, [2023-01-27T22:01:42.022347 #418147]  INFO -- : [1086c29d-9259-4ad7-8f68-072709085665]   Rendered plugins/onlyoffice_redmine/app/views/documents/show.html.erb within layouts/base (Duration: 23.1ms | Allocations: 5041)
I, [2023-01-27T22:01:42.042761 #418147]  INFO -- : [1086c29d-9259-4ad7-8f68-072709085665]   Rendered layout layouts/base.html.erb (Duration: 43.6ms | Allocations: 15369)
I, [2023-01-27T22:01:42.043209 #418147]  INFO -- : [1086c29d-9259-4ad7-8f68-072709085665] Completed 200 OK in 60ms (Views: 39.7ms | ActiveRecord: 7.7ms | Allocations: 18117)



**documentserver**:
[2023-01-27T22:01:36.685] [ERROR] [localhost] [18514_2023_01_27_19_59_29_UTC] [3] nodeJS - postData error: url = https://redmine.iccs.gr//onlyoffice/callback/18514/d01cf5c316e14ea2378fc94f6684cc83cc4ccd53?key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdHRhY2htZW50X2lkIjoxODUxNCwidHlwZSI6ImNhbGxiYWNrIn0.f_h7qiLmj5RYa50WAooOl7zshlKTmmq9FmGpNdZlte8;data = {"key":"18514_2023_01_27_19_59_29_UTC","status":1,"users":["3"],"actions":[{"type":1,"userid":"3"}],"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXkiOiIxODUxNF8yMDIzXzAxXzI3XzE5XzU5XzI5X1VUQyIsInN0YXR1cyI6MSwidXNlcnMiOlsiMyJdLCJhY3Rpb25zIjpbeyJ0eXBlIjoxLCJ1c2VyaWQiOiIzIn1dLCJpYXQiOjE2NzQ4NDk2OTYsImV4cCI6MTY3NDg0OTk5Nn0.QHJyoA85JFlFYhssrue-TngwVd4a_d6VoPtrPYhNDmI"} Error: Error response: statusCode:500; headers:{"date":"Fri, 27 Jan 2023 20:01:36 GMT","server":"Apache/2.4.54 (Debian)","x-request-id":"15d5ebf1-cdb7-4755-bdaf-a223cb31f430","x-runtime":"0.019585","x-powered-by":"Phusion Passenger(R) 6.0.16","content-length":"648","status":"500 Internal Server Error","connection":"close","content-type":"text/html; charset=utf-8"}; body:
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Redmine 500 error</title>
  <style>
    body {font-family: "Trebuchet MS", Georgia, "Times New Roman", serif; color: #303030; margin: 10px;}
    h1 {font-size:1.5em;}
    p {font-size:0.8em;}
  </style>
</head>
<body>
  <h1>Internal error</h1>
  <p>An error occurred on the page you were trying to access.<br />
  If you continue to experience problems please contact your Redmine administrator for assistance.</p>
  <p>If you are the Redmine administrator, check your log files for details about the error.</p>
  <p><a href="javascript:history.back()">Back</a></p>
</body>
</html>

    at Request._callback (/snapshot/server/build/server/Common/sources/utils.js)
    at Request.callback (/snapshot/server/build/server/Common/node_modules/request/request.js:185:22)
    at Request.emit (events.js:400:28)
    at Request.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:400:28)
    at IncomingMessage.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:519:28)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)



cat /etc/onlyoffice/documentserver/local.json
{
  "services": {
    "CoAuthoring": {
      "sql": {
        "type": "postgres",
        "dbHost": "localhost",
        "dbPort": "5432",
        "dbName": "xxx",
        "dbUser": "xxx",
        "dbPass": "xxx"
      },
      "redis": {
        "host": "localhost"
      },
      "token": {
        "enable": {
          "request": {
            "inbox": true,
            "outbox": true
          },
          "browser": true
        },
        "inbox": {
          "header": "Authorization"
        },
        "outbox": {
          "header": "Authorization"
        }
      },
      "secret": {
        "inbox": {
          "string": "1111"
        },
        "outbox": {
          "string": "1111"
        },
        "session": {
          "string": "1111"
        }
      }
    }
  },
  "rabbitmq": {
    "url": "amqp://guest:guest@localhost"
  }
}

i hope this helps

**Comment by jelenpivo** [comment]
Same error

**Comment by SergeyKorneyev** [comment]
Please check if the issue persists with the recently released version 3.0 of the plugin.

**Comment by LinneyS** [comment]
This issue was closed due to no response.
